name: 'mailchimp'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
test-paths: ["test"]
data-paths: ["data"]

models:
    mailchimp:
        fivetran:
            vars:
                - subs_activities_table: #schema.table
                - campaigns_table: #schema.table
                - list_members_table: #schema.table
                - lists_table: #schema.table
                - members_table: #schema.table
